
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always

app:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/concession
    username: root
    password: root